name: 'my_new_project'
version: '1.0.0'
config-version: 2
profile: 'default'

models:
  my_new_project:
    # Applies to all files under models/example/
    mart:
      +materialized: table
      finance:
      +schema: finance
    staging :
      +materialized: view
    
    

